# Generated by Django 4.2.16 on 2025-11-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_successstory_successstoryimage'),
    ]

    operations = [
    ]
